import {
  Settings2,
  Disc3,
  Droplets,
  Gauge,
  Lightbulb,
  Filter,
  CircleDot,
  Car,
} from "lucide-react";

export const categories = [
  {
    id: 1,
    label: "لوازم یدکی موتور",
    slug: "engine-parts",
    Icon: Settings2,
    iconBg: "bg-blue-500/15",
    iconColor: "text-blue-300",
    ringColor: "ring-blue-500/20",
    hoverRing: "group-hover:ring-blue-400/50",
    hoverShadow: "group-hover:shadow-blue-500/20",
    hoverBg: "group-hover:bg-blue-500/25",
  },
  {
    id: 2,
    label: "سیستم ترمز",
    slug: "brake-system",
    Icon: Disc3,
    iconBg: "bg-rose-500/15",
    iconColor: "text-rose-300",
    ringColor: "ring-rose-500/20",
    hoverRing: "group-hover:ring-rose-400/50",
    hoverShadow: "group-hover:shadow-rose-500/20",
    hoverBg: "group-hover:bg-rose-500/25",
  },
  {
    id: 3,
    label: "روغن و مایعات",
    slug: "oil-fluids",
    Icon: Droplets,
    iconBg: "bg-amber-500/15",
    iconColor: "text-amber-300",
    ringColor: "ring-amber-500/20",
    hoverRing: "group-hover:ring-amber-400/50",
    hoverShadow: "group-hover:shadow-amber-500/20",
    hoverBg: "group-hover:bg-amber-500/25",
  },
  {
    id: 4,
    label: "اکسسوری اسپورت",
    slug: "sport-accessories",
    Icon: Gauge,
    iconBg: "bg-emerald-500/15",
    iconColor: "text-emerald-300",
    ringColor: "ring-emerald-500/20",
    hoverRing: "group-hover:ring-emerald-400/50",
    hoverShadow: "group-hover:shadow-emerald-500/20",
    hoverBg: "group-hover:bg-emerald-500/25",
  },
  {
    id: 5,
    label: "سیستم روشنایی",
    slug: "lighting",
    Icon: Lightbulb,
    iconBg: "bg-yellow-500/15",
    iconColor: "text-yellow-300",
    ringColor: "ring-yellow-500/20",
    hoverRing: "group-hover:ring-yellow-400/50",
    hoverShadow: "group-hover:shadow-yellow-500/20",
    hoverBg: "group-hover:bg-yellow-500/25",
  },
  {
    id: 6,
    label: "فیلتر و هواکش",
    slug: "filters",
    Icon: Filter,
    iconBg: "bg-cyan-500/15",
    iconColor: "text-cyan-300",
    ringColor: "ring-cyan-500/20",
    hoverRing: "group-hover:ring-cyan-400/50",
    hoverShadow: "group-hover:shadow-cyan-500/20",
    hoverBg: "group-hover:bg-cyan-500/25",
  },
  {
    id: 7,
    label: "رینگ و تایر",
    slug: "wheels-tires",
    Icon: CircleDot,
    iconBg: "bg-purple-500/15",
    iconColor: "text-purple-300",
    ringColor: "ring-purple-500/20",
    hoverRing: "group-hover:ring-purple-400/50",
    hoverShadow: "group-hover:shadow-purple-500/20",
    hoverBg: "group-hover:bg-purple-500/25",
  },
  {
    id: 8,
    label: "لوازم داخلی",
    slug: "interior",
    Icon: Car,
    iconBg: "bg-orange-500/15",
    iconColor: "text-orange-300",
    ringColor: "ring-orange-500/20",
    hoverRing: "group-hover:ring-orange-400/50",
    hoverShadow: "group-hover:shadow-orange-500/20",
    hoverBg: "group-hover:bg-orange-500/25",
  },
];
