export { carCategories } from "./categories.jsx";
export { recentSearches, popularSearches } from "./search";
export { brandsData } from "./brands";
export { sliderData } from "./sliderData";
export { amazingOfferProducts } from "./products";
export { popularProducts } from "./popularProducts";
export { recentArticles } from "./RecentArticles.js";
export { footerLinks } from "./footerLinks";
export { contactItems } from "./contactsItem.jsx";
export { teamMembers } from "./teamMembers.js";
export { mobileCategoris } from "./mobileCategoris.jsx";
