export const popularProducts = [
  {
    id: 1,
    name: "روغن موتور کاسترول EDGE 5W-40",
    brand: "Castrol",
    category: "لوازم مصرفی",
    image: "/images/products/oil-castrol.jpg",
    price: 850000,
    originalPrice: 1200000,
    discount: 29,
    rating: 4.8,
    reviewCount: 342,
    salesCount: 567,
    stock: "موجود",
    badge: "پرفروش",
    features: ["4 لیتری", "سینتتیک", "مناسب بنزینی"],
  },
  {
    id: 2,
    name: "باتری اطلس 66 آمپر پریمیوم",
    brand: "Atlas",
    category: "برق و باتری",
    image: "/images/products/battery-atlas.jpg",
    price: 3500000,
    originalPrice: 4200000,
    discount: 17,
    rating: 4.6,
    reviewCount: 198,
    salesCount: 423,
    stock: "موجود",
    badge: "پرفروش",
    features: ["18 ماه گارانتی", "66 آمپر", "ساخت ایران"],
  },
  {
    id: 3,
    name: "لنت ترمز جلو ABS پراید",
    brand: "ABS",
    category: "قطعات یدکی",
    image: "/images/products/brake-pad.jpg",
    price: 420000,
    originalPrice: null,
    discount: 0,
    rating: 4.4,
    reviewCount: 234,
    salesCount: 891,
    stock: "موجود",
    badge: null,
    features: ["اصل", "کم صدا", "مقاوم"],
  },
  {
    id: 4,
    name: "فیلتر هوای K&N قابل شستشو",
    brand: "K&N",
    category: "لوازم مصرفی",
    image: "/images/products/air-filter-kn.jpg",
    price: 1650000,
    originalPrice: 1950000,
    discount: 15,
    rating: 4.9,
    reviewCount: 127,
    salesCount: 345,
    stock: "موجود",
    badge: "پرفروش",
    features: ["قابل شستشو", "افزایش قدرت", "عمر بالا"],
  },
  {
    id: 5,
    name: "دیسک چرخ جلو بوش پژو 206",
    brand: "Bosch",
    category: "قطعات یدکی",
    image: "/images/products/brake-disc-bosch.jpg",
    price: 2850000,
    originalPrice: 3500000,
    discount: 19,
    rating: 4.7,
    reviewCount: 156,
    salesCount: 267,
    stock: "موجود",
    badge: null,
    features: ["اصل آلمان", "ضد زنگ", "دوام بالا"],
  },
  {
    id: 6,
    name: "شمع موتور بوش پلاتینیوم",
    brand: "Bosch",
    category: "لوازم مصرفی",
    image: "/images/products/spark-plug.jpg",
    price: 180000,
    originalPrice: null,
    discount: 0,
    rating: 4.5,
    reviewCount: 445,
    salesCount: 1234,
    stock: "موجود",
    badge: "پرفروش",
    features: ["بسته 4 عددی", "پلاتینیوم", "عمر 100 هزار کیلومتر"],
  },
  {
    id: 7,
    name: "ضربه گیر گاز ایران یدک پژو پارس",
    brand: "ایران یدک",
    category: "قطعات یدکی",
    image: "/images/products/shock-absorber.jpg",
    price: 1950000,
    originalPrice: 2400000,
    discount: 19,
    rating: 4.3,
    reviewCount: 89,
    salesCount: 178,
    stock: "موجود",
    badge: null,
    features: ["گاز", "جفت", "12 ماه گارانتی"],
  },
  {
    id: 8,
    name: "دسته موتور هیدرولیک مدرن سمند",
    brand: "Modern",
    category: "قطعات یدکی",
    image: "/images/products/engine-mount.jpg",
    price: 680000,
    originalPrice: 850000,
    discount: 20,
    rating: 4.4,
    reviewCount: 167,
    salesCount: 412,
    stock: "موجود",
    badge: null,
    features: ["هیدرولیک", "کاهش ارتعاش", "ساخت تایوان"],
  },
  {
    id: 9,
    name: "روغن گیربکس کاسترول ATF",
    brand: "Castrol",
    category: "لوازم مصرفی",
    image: "/images/products/oil-gear.jpg",
    price: 520000,
    originalPrice: null,
    discount: 0,
    rating: 4.7,
    reviewCount: 98,
    salesCount: 256,
    stock: "موجود",
    badge: null,
    features: ["1 لیتری", "گیربکس اتوماتیک", "اصل انگلیس"],
  },
  {
    id: 10,
    name: "دینام 90 آمپر وستن پراید",
    brand: "Vasten",
    category: "برق و باتری",
    image: "/images/products/alternator.jpg",
    price: 2750000,
    originalPrice: 3200000,
    discount: 14,
    rating: 4.5,
    reviewCount: 112,
    salesCount: 198,
    stock: "موجود",
    badge: "پرفروش",
    features: ["90 آمپر", "نو", "12 ماه گارانتی"],
  },
];
