export const popularProducts = [
  {
    id: 1,
    name: "روغن موتور کاسترول 5W-40",
    brand: "Castrol",
    category: "لوازم مصرفی",
    image: "/images/products/oil-castrol.jpg",
    price: "850000",
    originalPrice: "1200000",
    discount: 29,
    rating: 4.8,
    reviewCount: 156,
    salesCount: 342,
    stock: "موجود",
    badge: "پرفروش",
    features: ["4 لیتری", "مناسب خودروهای بنزینی", "گارانتی اصالت"],
  },
  {
    id: 2,
    name: "باتری اطلس 66 آمپر",
    brand: "Atlas",
    category: "برق و باتری",
    image: "/images/products/battery-atlas.jpg",
    price: "3500000",
    originalPrice: null,
    discount: 0,
    rating: 4.6,
    reviewCount: 89,
    salesCount: 178,
    stock: "موجود",
    badge: null,
    features: ["18 ماه گارانتی", "قدرت جریان بالا", "مناسب پراید و پژو"],
  },
];
